### ISSUE TITLE
safe to mount /etc/fonts?

### ISSUE THREAD

**Issue by Radvendii** [nixpak/nixpak#28]
Is there a security concern with mounting /etc/fonts? I'm confused why there's infrastructure in nixpak for creating a separate font config for the bubblewrapped application.

**Comment by max-privatevoid** [comment]
I don't think it's insecure, but it is impure. You'd need to mount all the directories where the actual fonts are stored as well. I want NixPak to offer the possbility to make fully self-contained apps, which is why there's an option to bundle graphics drivers as well for example.

**Comment by Radvendii** [comment]
Ah I see. I'm running on NixOS, so the fonts should be in the nix store which is mounted in its entirety (readonly) anyways.

Thanks.
