### ISSUE TITLE
Deal with multiple executables

### ISSUE THREAD

**Issue by max-privatevoid** [nixpak/nixpak#3]

**Comment by max-privatevoid** [comment]
This is covered by https://github.com/nixpak/nixpak/commit/2d0a7e92ef13b1d722dfa7696ac8a29f3b0ec846 and some commits following it. An example showcasing the feature has also been added https://github.com/nixpak/nixpak/blob/3dae37ae90fd1de3bb905c18f422311a407df484/examples/multiple-executables.nix

**Comment by tmarkov** [comment]
Hi! Why not automatically wrap all the executables in `${pkgs.package}/bin`?
