### ISSUE TITLE
Recommended GUI program package examples?

### ISSUE THREAD

**Issue by alxpettit** [nixpak/nixpak#61]
Are there any recommended working examples of complex GUI applications -- e.g. Firefox, Discord, Element, etc?

**Comment by alxpettit** [comment]
Found one here: https://codeberg.org/Liassica/nixpak-pkgs/src/branch/main/pkgs/browsers/firefox/default.nix

**Comment by Liassica** [comment]
The file linked above is now at https://codeberg.org/Liassica/nixpak-pkgs-old/src/branch/main/pkgs/browsers/firefox/default.nix and I've a [new repo](https://codeberg.org/Liassica/nixpak-pkgs) with a [slightly different firefox package](https://codeberg.org/Liassica/nixpak-pkgs/src/branch/main/pkgs/by-name/fi/firefox/default.nix), for anyone looking at this later.
