### ISSUE TITLE
Chromium IPC doesn't work for separate instances

### ISSUE THREAD

**Issue by alxpettit** [nixpak/nixpak#63]
This is a weird one. Although chromium IPC seems to work fine for splitting apart and rejoining tabs, _new_ instances of chromium do not seem to be able to coordinate handling their databases. Instead, it separately tries to open the database, fails because it's locked, and then I get the following:

![image](https://github.com/nixpak/nixpak/assets/28266167/fe1f22d1-99a2-48c9-8e15-8f0c1f8685ca)

Various electron apps also behave in a similar way (although they just display their login screens after failing silently).

Firefox does _not_ show this issue at all -- it works completely as desired.

I should note that `shareIpc` is set to true, and my experimental profile is pretty lax right now. Do you know anything about this, @max-privatevoid?

**Comment by max-privatevoid** [comment]
Chromium does IPC via /tmp, so you need to make sure that /tmp is shared across all the instances, e.g. by bind-mounting a shared directory: https://github.com/nixpak/pkgs/blob/master/pkgs/browsers/chromium/default.nix#L14-L20

**Comment by alxpettit** [comment]
Awesome, that did the trick! Thanks! :D
